name: Suggestion
description: Suggest an idea or an improvement
title: "[Suggestion] "
labels: ["suggestion"]
body:
  - type: dropdown
    id: mod
    attributes:
      label: Mod concerned
      options:
        - "Create: Belgian Snacks"
        - CustomPerm
        - Better Creative
        - Creative Admin
    validations:
      required: true

  - type: textarea
    id: idea
    attributes:
      label: Your idea
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why it would be useful
